Repository DAT-05-02/P5, pull requests merged in 2023-10, with the labels that each got.

#43 LBP experimentation
  README.md
  core/data/feature.py
  core/data/fetch.py
  requirements.txt
Labels: duplicate, enhancement, research

#46 Git LFS Cache
  .github/workflows/py_action.yml
Labels: bug

#65 Better fetching, database setup, more logging tools.
  .github/workflows/py_action.yml
  .gitignore
  .pre-commit-config.yaml
  README.md
  core/data/feature.py
  core/data/fetch.py
  core/run.py
  core/util/logging/__init__.py
  core/util/logging/logable.py
  core/util/util.py
  requirements.txt
  test/test_data/test_fetch.py
Labels: documentation, enhancement, devops

#71 Cache venv in Github Actions
  .github/workflows/py_action.yml
Labels: devops

#82 Feature checker
  core/data/feature.py
Labels: enhancement

#83 fixed issue #72 and refactored tests
  core/data/feature.py
  core/data/fetch.py
  core/run.py
  core/util/constants.py
  pyproject.toml
  runTensorboard.bat
  test/test_data/test_feature.py
  test/test_data/test_fetch.py
Labels: bug, enhancement
